apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-demo
  namespace: argocd
spec:
  destinations:
    - namespace: gitops-demo
      server: https://kubernetes.default.svc
  sourceRepos:
    - 'https://github.com/psmohankumar/DevOps-Home-Lab-2025.git'
  clusterResourceWhitelist: []        # no cluster-scoped perms
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'                       # namespace-scoped resources only
  orphanedResources:
    warn: true
  # Removed problematic sync windows for now
  # syncWindows:
  #   - kind: allow
  #     schedule: "0 22 * * 1-5"  # 10 PM Mon-Fri
  #     duration: "8h"
  #     applications: ["gitops-demo-*"]
